from __future__ import annotations

# Project-level validation taxonomy
PRJ_PATH_ESCAPE = "PRJ010"
PRJ_GOVERNANCE_MISSING = "PRJ011"
PRJ_PARSE_ERROR = "PRJ101"
PRJ_SCHEMA_ERROR = "PRJ102"
PRJ_SEMANTIC_ERROR = "PRJ103"

# Task-level validation taxonomy
TASK_PARSE_ERROR = "TASK100"
TASK_SCHEMA_ERROR = "TASK101"
TASK_STATUS_ERROR = "TASK200"
TASK_TRANSITION_ERROR = "TASK201"

# Policy-level taxonomy
POL_STATE_VIOLATION = "POL200"
POL_PERMISSION_DENIED = "POL201"
